CREATE DATABASE php_hackathon_db;

USE php_hackathon_db;


CREATE TABLE IF NOT EXISTS DEPARTMENT(
  DEPARTMENT_ID  INT (255) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DEPARTMENT_NAME VARCHAR (255) NOT NULL

);
CREATE TABLE IF NOT EXISTS user_info(
  EMPLOYEE_ID INT (6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USERNAME VARCHAR (255) NOT NULL,
  PASSWORD VARCHAR (255) NOT NULL,
  FIRST_NAME VARCHAR (255) NOT NULL,
  LAST_NAME VARCHAR (255) NOT NULL,
  MIDDLE_NAME VARCHAR (255) NOT NULL,
  EMAIL_ADDRESS VARCHAR (255) NOT NULL,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE IF NOT EXISTS UNIT(
  UNIT_ID INT (6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  UNIT_NAME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJECT (
  PROJECT_ID INT (6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PROJECT_NAME VARCHAR(255) NOT NULL,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
  DESCRIPTION VARCHAR (255) NOT NULL,
  TOTAL_BUDGET FLOAT (255) NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  PERCENTAGE DECIMAL (5,2)
);

CREATE TABLE IF NOT EXISTS RECIPIENT (
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
  TARGET_RECIPIENT INT (255),
  ACTUAL_RECIPIENT INT (255),
  FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID),
  PERCENT_RECIPIENT DECIMAL(5,2)
);

CREATE TABLE IF NOT EXISTS EXPENDITURES (
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
  BUDGET_ALLOC INT (255),
  ACTUAL_SPENT INT (255),
  PERCENT_TOTAL DECIMAL (5,2)
);
