CREATE DATABASE php_hackathon_db;

USE php_hackathon_db;


CREATE TABLE IF NOT EXISTS DEPARTMENT(
  DEPARTMENT_ID  INT (255) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DEPARTMENT_NAME VARCHAR (255) NOT NULL

);
CREATE TABLE IF NOT EXISTS user_info(
  EMPLOYEE_ID INT (6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  EMAIL_ADDRESS VARCHAR (255) NOT NULL,
  PASSWORD VARCHAR (255) NOT NULL,
  FIRST_NAME VARCHAR (255) NOT NULL,
  LAST_NAME VARCHAR (255) NOT NULL,
  MIDDLE_NAME VARCHAR (255) NOT NULL,
  DEPARTMENT_ID INT (255) NOT NULL,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
)ENGINE=MYISAM;

CREATE TABLE IF NOT EXISTS UNIT(
  UNIT_ID INT (6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  UNIT_NAME VARCHAR (255) NOT NULL
)ENGINE=MYISAM;

CREATE TABLE IF NOT EXISTS PROJECT (
  PROJECT_ID INT (6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PROJECT_NAME VARCHAR(255) NOT NULL,
  DEPARTMENT_ID INT(255) NOT NULL,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
  DESCRIPTION VARCHAR (255) NOT NULL,
  TOTAL_BUDGET DOUBLE NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  PERCENTAGE DECIMAL (5,2)
)ENGINE=MYISAM;

CREATE TABLE IF NOT EXISTS RECIPIENT (
  PROJECT_ID INT(255) NOT NULL,
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
  TARGET_RECIPIENT INT (255),
  ACTUAL_RECIPIENT INT (255),
  UNIT_ID INT(255) NOT NULL,
  FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID),
  PERCENT_RECIPIENT DECIMAL(5,2)
)ENGINE=MYISAM;

CREATE TABLE IF NOT EXISTS EXPENDITURES (
  PROJECT_ID INT(255) NOT NULL,
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
  BUDGET_ALLOC INT (255),
  ACTUAL_SPENT INT (255),
  PERCENT_TOTAL DECIMAL (5,2)
)ENGINE=MYISAM;
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (1, 'DSWD');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (2, 'DOF-SSS');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (3, 'DOH');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (4, 'DOF-BTr');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (5, 'DA');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (6, 'DOLE');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (7, 'DILG-PNP');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (8, 'DND-OCD');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (9, 'DND-AFP');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (11, 'DOLE-OWWA');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (12, 'DOST');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (13, 'DOJ-NBI');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (14, 'OEO-OPAPP');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (15, 'DFA');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (16, 'DILG-BFP');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (17, 'DILG-BJMP');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (18, 'DND-VMMC');
INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (19, 'LGU');
